#!/bin/bash

i=1
while [ $i -le 59 ]
do
    head -1 113 >> /home/vova/script/test/1/c"$i"

    echo "i=$i" >> /home/vova/script/test/1/c"$i"

    head -66 mp >> /home/vova/script/test/1/c"$i"



i=$[$i+1]

done