#!/bin/bash

i=1
while [ $i -le 59 ]
do

#записываем первую строчку #!/bin/bash
    head -1 113 >> /home/vova/7/script/1/c"$i"
#присваеваем номер
    echo "i=$i" >> /home/vova/7/script/1/c"$i"

#вставляем сам текст
    head -38 mp1 >> /home/vova/7/script/1/c"$i"

#Делаем исплняемыми chmod +x -R 1

i=$[$i+1]

done