#!/bin/bash

amixer set Master unmute 25

mplayer -nocache -softvol `head -1 /home/vova/public_html/server/radio/radio.txt` -af extrastereo=0,volume=`head -1 /home/vova/public_html/server/volume/volume.txt`

