#!/bin/bash

amixer set Master unmute 25

ps -ax | grep mplayer > k.txt;kill `head -c10 k.txt`

sleep 2


mplayer -nocache -softvol `head -1 /home/vova/public_html/server/radio/radio.txt` -af extrastereo=0,volume=`head -1 /home/vova/public_html/server/volume/volume.txt`

